version: '2'

services:
  db_server:
    image: mysql:5.7
    container_name: db_server
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/initdb.d:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myPassword #mysql root password
      MYSQL_DATABASE: myDbName #database name
      MYSQL_USER: myDbUser #database username
      MYSQL_PASSWORD: myDbPasswrd #database user password

  wordpress:
    depends_on:
      - db_server
    image: wordpress:5.7-php7.4
    container_name: wordpress
    ports:
      - "1234:8080"
    restart: always
    links:
      - db_server:mysql
    volumes:
      - ./src:/var/www/html
